public class Main {

    public static void main(String[] args) throws Exception {
        ListProduct list = new ListProduct();

        list.addProduct("Mouse Gaming RGB", 250000, 4.9);
        list.addProduct("Beras Merah Organik 2kg", 45000, 4.7);
        list.addProduct("Kaos Polos Katun", 85000, 4.8);
        list.addProduct("Sambal Bawang Pedas", 18000, 4.9);
        list.addProduct("Sereal Coklat Granola", 42000, 4.6);
        list.addProduct("Filter Air Minum", 120000, 4.7);
        list.addProduct("Baterai Isi Ulang AA", 65000, 4.5);
        list.addProduct("Jas Hujan Setelan", 75000, 4.6);
        list.addProduct("Kecap Asin Jepang", 28000, 4.8);
        list.addProduct("Teh Hijau Bubuk Matcha", 55000, 4.9);
        list.addProduct("Pasta Gigi Sensitif", 15000, 4.7);
        list.addProduct("Lampu Darurat LED", 95000, 4.8);
        list.addProduct("Obat Tetes Mata", 12000, 4.6);
        list.addProduct("Yogurt Plain Kental", 11000, 4.5);
        list.addProduct("Spatula Silikon Set", 60000, 4.9);
        list.addProduct("Buku Agenda 2025", 70000, 4.7);
        list.addProduct("Headset Bluetooth TWS", 350000, 4.8);
        list.addProduct("Minyak Zaitun Extra Virgin", 85000, 5.0);
        list.addProduct("Kopi Arabika Toraja", 60000, 4.9);
        list.addProduct("Sabun Cuci Muka Pria", 28000, 4.7);
        list.addProduct("Gembok Sidik Jari", 220000, 4.8);
        list.addProduct("Tali Skipping Digital", 90000, 4.6);
        list.addProduct("Pembersih Kerak Kamar Mandi", 22000, 4.5);
        list.addProduct("Roti Gandum Utuh", 19000, 4.7);
        list.addProduct("Powerbank 20000mAh", 280000, 4.9);
        list.addProduct("Selai Kacang Organik", 40000, 4.8);
        list.addProduct("Speaker Aktif Komputer", 450000, 4.7);
        list.addProduct("Pupuk NPK Mutiara", 25000, 4.6);
        list.addProduct("Masker KN95 (Isi 10)", 35000, 4.8);
        list.addProduct("Susu Kental Manis", 11000, 4.5);
        list.addProduct("Keyboard Wireless Combo", 290000, 4.7);
        list.addProduct("Webcam 1080p", 210000, 4.6);
        list.addProduct("Termos Air Panas 1L", 150000, 4.9);
        list.addProduct("Keripik Tempe Sagu", 14000, 4.8);
        list.addProduct("Madu Manuka", 250000, 5.0);
        list.addProduct("Stapler Tembak", 80000, 4.5);
        list.addProduct("Payung Golf Besar", 120000, 4.7);
        list.addProduct("Blender Jus Portabel", 180000, 4.8);
        list.addProduct("Timbangan Dapur Digital", 95000, 4.9);
        list.addProduct("Pengharum Mobil Kopi", 25000, 4.6);
        list.addProduct("Helm Sepeda", 175000, 4.7);
        list.addProduct("Kacamata Anti Radiasi", 130000, 4.8);
        list.addProduct("Bantal Leher Memory Foam", 85000, 4.9);
        list.addProduct("Gunting Dahan", 65000, 4.5);
        list.addProduct("Lampu Meja Belajar", 110000, 4.7);
        list.addProduct("Rak Sepatu Susun", 90000, 4.6);
        list.addProduct("Charger Laptop Universal", 200000, 4.8);
        list.addProduct("Dompet Kulit Asli", 180000, 4.9);
        list.addProduct("Ikat Pinggang Pria", 95000, 4.7);
        list.addProduct("Jam Tangan Digital", 250000, 4.8);
        list.addProduct("Cokelat Hitam 85%", 35000, 5.0);
        list.addProduct("Granola Bar Kacang", 12000, 4.6);
        list.addProduct("Susu Kedelai Bubuk", 38000, 4.7);
        list.addProduct("Bumbu Nasi Goreng Instan", 4000, 4.9);
        list.addProduct("Tepung Roti Kasar", 15000, 4.5);
        list.addProduct("Cuka Apel", 45000, 4.8);
        list.addProduct("Deterjen Bubuk Anti Noda", 32000, 4.7);
        list.addProduct("Hand Sanitizer Gel", 18000, 4.6);
        list.addProduct("Tisu Basah Antiseptik", 13000, 4.8);
        list.addProduct("Vitamin C 500mg", 40000, 4.9);
        list.addProduct("Minyak Ikan Omega-3", 95000, 4.8);
        list.addProduct("Body Lotion UV Protection", 28000, 4.7);
        list.addProduct("Pomade Rambut Pria", 50000, 4.9);
        list.addProduct("Cat Air 12 Warna", 35000, 4.6);
        list.addProduct("Kanvas Lukis 30x40", 25000, 4.5);
        list.addProduct("Kuas Lukis Set", 45000, 4.7);
        list.addProduct("Buku Gambar A3", 22000, 4.8);
        list.addProduct("Pensil Warna 24", 60000, 4.9);
        list.addProduct("Tas Ransel Laptop", 320000, 4.8);
        list.addProduct("Koper Kabin Hardcase", 550000, 4.7);
        list.addProduct("Sepatu Lari", 450000, 4.9);
        list.addProduct("Sandal Gunung", 180000, 4.6);
        list.addProduct("Celana Jeans Pria", 280000, 4.8);
        list.addProduct("Kemeja Flanel", 195000, 4.7);
        list.addProduct("Jaket Hoodie Zipper", 220000, 4.9);
        list.addProduct("Topi Kupluk Rajut", 60000, 4.5);
        list.addProduct("Sarung Tangan Motor", 75000, 4.7);
        list.addProduct("Masker Buff", 30000, 4.6);
        list.addProduct("Gembok Sepeda", 90000, 4.8);
        list.addProduct("Lampu Sepeda LED", 65000, 4.9);
        list.addProduct("Botol Minum Olahraga", 55000, 4.7);
        list.addProduct("Handuk Mikrofiber", 80000, 4.8);
        list.addProduct("Matras Yoga", 150000, 4.9);
        list.addProduct("Dumbbell 2kg", 95000, 4.6);
        list.addProduct("Tali Resistensi Set", 120000, 4.7);
        list.addProduct("Bola Basket", 140000, 4.8);
        list.addProduct("Raket Badminton", 250000, 4.9);
        list.addProduct("Shuttlecock (Isi 12)", 85000, 4.7);
        list.addProduct("Meja Lipat Laptop", 130000, 4.8);
        list.addProduct("Kursi Gaming", 1200000, 4.9);
        list.addProduct("Monitor Komputer 24 inch", 1800000, 4.7);
        list.addProduct("Printer All-in-One", 950000, 4.6);
        list.addProduct("Tinta Printer Hitam", 150000, 4.8);
        list.addProduct("Kertas HVS A4 80gr", 55000, 4.9);
        list.addProduct("Amplop Putih (Isi 100)", 25000, 4.7);
        list.addProduct("Map Kertas", 5000, 4.5);
        list.addProduct("Stabilo Set 4 Warna", 28000, 4.8);
        list.addProduct("Tip-Ex Cair", 7000, 4.6);
        list.addProduct("Binder A5", 45000, 4.9);
        list.addProduct("Isi Binder Loose Leaf", 20000, 4.7);

        // 100 data

        list.addProduct("Kalkulator Scientific", 120000, 4.8);
        list.addProduct("Flashdisk 64GB", 95000, 4.9);
        list.addProduct("Kartu Memori 128GB", 180000, 4.7);
        list.addProduct("Hard Disk Eksternal 1TB", 750000, 4.8);
        list.addProduct("SSD Eksternal 512GB", 900000, 4.9);
        list.addProduct("Router WiFi", 350000, 4.6);
        list.addProduct("Kabel LAN 5 Meter", 40000, 4.5);
        list.addProduct("Stop Kontak 4 Lubang", 65000, 4.7);
        list.addProduct("Senter LED Super Terang", 110000, 4.8);
        list.addProduct("Pisau Dapur Set", 130000, 4.9);
        list.addProduct("Talenan Kayu", 50000, 4.7);
        list.addProduct("Panci Presto 4L", 280000, 4.8);
        list.addProduct("Wajan Teflon Anti Lengket", 150000, 4.9);
        list.addProduct("Sodet Stainless Steel", 35000, 4.6);
        list.addProduct("Mangkuk Keramik", 25000, 4.8);
        list.addProduct("Piring Melamin", 18000, 4.7);
        list.addProduct("Gelas Kaca Set (Isi 6)", 75000, 4.9);
        list.addProduct("Sendok Garpu Set", 90000, 4.8);
        list.addProduct("Botol Saus", 15000, 4.5);
        list.addProduct("Toples Kaca Kedap Udara", 40000, 4.7);
        list.addProduct("Kotak Bekal Makan", 60000, 4.9);
        list.addProduct("Termos Nasi", 120000, 4.6);
        list.addProduct("Setrika Uap", 220000, 4.8);
        list.addProduct("Meja Setrika Lipat", 180000, 4.7);
        list.addProduct("Jemuran Baju Aluminium", 250000, 4.9);
        list.addProduct("Hanger Baju (Isi 10)", 35000, 4.8);
        list.addProduct("Pewangi Pakaian Semprot", 18000, 4.7);
        list.addProduct("Sikat WC", 15000, 4.5);
        list.addProduct("Ember Plastik", 25000, 4.6);
        list.addProduct("Gayung Mandi", 8000, 4.8);
        list.addProduct("Keset Kaki Mikrofiber", 45000, 4.9);
        list.addProduct("Tempat Sampah Injak", 80000, 4.7);
        list.addProduct("Obat Kumur Antiseptik", 22000, 4.8);
        list.addProduct("Benang Gigi", 15000, 4.6);
        list.addProduct("Sikat Gigi Elektrik", 350000, 4.9);
        list.addProduct("Sabun Muka Batang", 12000, 4.7);
        list.addProduct("Krim Mata Anti Kerut", 95000, 4.8);
        list.addProduct("Serum Vitamin C", 120000, 4.9);
        list.addProduct("Sunscreen SPF 50", 85000, 5.0);
        list.addProduct("Lip Balm", 25000, 4.7);
        list.addProduct("Cat Kuku Merah", 18000, 4.6);
        list.addProduct("Aseton Pembersih Cat Kuku", 12000, 4.5);
        list.addProduct("Pinset Alis", 9000, 4.8);
        list.addProduct("Gunting Kuku", 7000, 4.9);
        list.addProduct("Sisir Rambut Anti Kusut", 35000, 4.7);
        list.addProduct("Hair Dryer Mini", 150000, 4.8);
        list.addProduct("Catokan Rambut", 280000, 4.9);
        list.addProduct("Vitamin Rambut", 20000, 4.6);
        list.addProduct("Gel Rambut Pria", 18000, 4.5);
        list.addProduct("Kopi Luwak Asli", 150000, 5.0);
        list.addProduct("Teh Earl Grey", 45000, 4.8);
        list.addProduct("Cokelat Panas Bubuk", 38000, 4.7);
        list.addProduct("Sirup Maple", 75000, 4.9);
        list.addProduct("Saus Barbeque", 28000, 4.6);
        list.addProduct("Mayones Original", 22000, 4.8);
        list.addProduct("Mustard Kuning", 18000, 4.7);
        list.addProduct("Garam Himalaya", 25000, 4.9);
        list.addProduct("Lada Hitam Bubuk", 15000, 4.8);
        list.addProduct("Bawang Putih Bubuk", 12000, 4.7);
        list.addProduct("Kaldu Jamur Bubuk", 20000, 4.9);
        list.addProduct("Daun Salam Kering", 8000, 4.5);
        list.addProduct("Kayu Manis Batang", 14000, 4.8);
        list.addProduct("Cengkeh Utuh", 16000, 4.7);
        list.addProduct("Kunyit Bubuk", 10000, 4.6);
        list.addProduct("Jahe Merah Instan", 35000, 4.9);
        list.addProduct("Bihun Jagung", 9000, 4.5);
        list.addProduct("Makaroni Spiral", 12000, 4.7);
        list.addProduct("Spaghetti La Fonte", 18000, 4.8);
        list.addProduct("Saus Bolognaise", 25000, 4.9);
        list.addProduct("Minyak Wijen", 30000, 4.8);
        list.addProduct("Kacang Mede Panggang", 55000, 4.9);
        list.addProduct("Kacang Almond Mentah", 65000, 4.7);
        list.addProduct("Kismis Kering", 22000, 4.6);
        list.addProduct("Kurma Tunisia", 45000, 4.8);
        list.addProduct("Manisan Buah Kering", 35000, 4.7);
        list.addProduct("Agar-agar Swallow", 5000, 4.9);
        list.addProduct("Jelly Nutrijell", 6000, 4.8);
        list.addProduct("Santan Kara", 4000, 4.7);
        list.addProduct("Susu Evaporasi", 15000, 4.9);
        list.addProduct("Cokelat Masak Batang", 22000, 4.8);
        list.addProduct("Tepung Maizena", 8000, 4.6);
        list.addProduct("Baking Powder", 6000, 4.5);
        list.addProduct("Soda Kue", 5000, 4.7);
        list.addProduct("Vanili Bubuk", 3000, 4.8);
        list.addProduct("Pewarna Makanan Merah", 4000, 4.9);
        list.addProduct("Meses Coklat", 12000, 4.7);
        list.addProduct("Keju Parmesan Bubuk", 35000, 4.8);
        list.addProduct("Bubur Bayi Instan", 18000, 4.9);
        list.addProduct("Biskuit Bayi", 15000, 4.7);
        list.addProduct("Minyak Telon", 28000, 4.8);
        list.addProduct("Bedak Bayi", 12000, 4.6);
        list.addProduct("Sabun Mandi Bayi", 25000, 4.9);
        list.addProduct("Shampo Bayi", 22000, 4.8);
        list.addProduct("Tisu Basah Bayi", 18000, 4.7);
        list.addProduct("Botol Susu Bayi", 45000, 4.9);
        list.addProduct("Dot Silikon", 15000, 4.8);
        list.addProduct("Sikat Botol", 12000, 4.7);
        list.addProduct("Sterilizer Botol", 250000, 4.9);
        list.addProduct("Gendongan Bayi", 180000, 4.8);
        list.addProduct("Mainan Gigitan Bayi", 35000, 4.7);

        // 200 data

        list.addProduct("Buku Cerita Anak", 50000, 4.9);
        list.addProduct("Puzzle Edukasi", 75000, 4.8);
        list.addProduct("Lego Klasik", 220000, 5.0);
        list.addProduct("Mobil-mobilan Remote Control", 180000, 4.7);
        list.addProduct("Boneka Beruang", 120000, 4.9);
        list.addProduct("Action Figure Superhero", 95000, 4.8);
        list.addProduct("Papan Catur Kayu", 150000, 4.7);
        list.addProduct("Kartu Uno", 25000, 4.9);
        list.addProduct("Monopoli Internasional", 120000, 4.8);
        list.addProduct("Gitar Akustik", 550000, 4.9);
        list.addProduct("Ukulele Soprano", 250000, 4.7);
        list.addProduct("Harmonika", 95000, 4.6);
        list.addProduct("Kamera DSLR Canon", 5500000, 4.9);
        list.addProduct("Lensa Kamera 50mm", 1200000, 4.8);
        list.addProduct("Tripod Kamera", 280000, 4.7);
        list.addProduct("Tas Kamera Ransel", 450000, 4.9);
        list.addProduct("Drone DJI Mini", 4800000, 5.0);
        list.addProduct("Smartwatch", 750000, 4.8);
        list.addProduct("Tablet Android 10 inch", 2200000, 4.7);
        list.addProduct("Laptop Core i5", 8500000, 4.9);
        list.addProduct("Mousepad Gaming", 80000, 4.8);
        list.addProduct("Cooling Pad Laptop", 120000, 4.7);
        list.addProduct("Tinta Stempel", 15000, 4.5);
        list.addProduct("Bak Stempel", 12000, 4.6);
        list.addProduct("Klip Kertas", 5000, 4.8);
        list.addProduct("Cutter", 9000, 4.7);
        list.addProduct("Penggaris Besi 30cm", 11000, 4.9);
        list.addProduct("Jangka", 15000, 4.8);
        list.addProduct("Kacamata Renang", 85000, 4.7);
        list.addProduct("Baju Renang Pria", 120000, 4.6);
        list.addProduct("Papan Seluncur", 450000, 4.9);
        list.addProduct("Bola Voli", 130000, 4.8);
        list.addProduct("Net Voli", 250000, 4.7);
        list.addProduct("Sepatu Futsal", 380000, 4.9);
        list.addProduct("Kaos Tim Futsal", 150000, 4.8);
        list.addProduct("Sarung Tangan Kiper", 180000, 4.7);
        list.addProduct("Dekker Pelindung Kaki", 75000, 4.6);
        list.addProduct("Cone Latihan", 50000, 4.5);
        list.addProduct("Tenda Camping (Kapasitas 4)", 450000, 4.9);
        list.addProduct("Sleeping Bag", 180000, 4.8);
        list.addProduct("Kompor Portable", 150000, 4.7);
        list.addProduct("Gas Kaleng", 25000, 4.9);
        list.addProduct("Nesting Set (Alat Masak Camping)", 220000, 4.8);
        list.addProduct("Lampu Tenda", 80000, 4.7);
        list.addProduct("Pisau Lipat Multifungsi", 120000, 4.9);
        list.addProduct("P3K Kit Mini", 65000, 4.8);
        list.addProduct("Kopi Sachet Susu", 2500, 5.0);
        list.addProduct("Air Purifier", 950000, 4.9);
        list.addProduct("Kerupuk Udang Finna", 18000, 4.9);
        list.addProduct("Pocari Sweat Kaleng", 7500, 4.8);
        list.addProduct("Bimoli Minyak Goreng 1L", 22000, 4.7);
        list.addProduct("Kacang Garuda Rosta", 13000, 4.9);
        list.addProduct("Ultra Milk Stroberi 250ml", 7000, 4.8);
        list.addProduct("Good Day Cappuccino", 3000, 5.0);
        list.addProduct("Saus Sambal ABC", 8000, 4.7);
        list.addProduct("Beng-Beng Coklat", 2500, 4.9);
        list.addProduct("Chitato Sapi Panggang", 12500, 4.8);
        list.addProduct("SilverQueen Chunky Bar", 15000, 5.0);
        list.addProduct("Teh Kotak Jasmine", 4500, 4.8);
        list.addProduct("Indomie Soto Mie", 3200, 4.9);
        list.addProduct("Pop Mie Rasa Bakso", 6500, 4.7);
        list.addProduct("Kecap Bango Manis", 21000, 5.0);
        list.addProduct("Susu Bendera Coklat", 10000, 4.6);
        list.addProduct("Energen Sereal Coklat", 2000, 4.8);
        list.addProduct("Tango Wafer Vanila", 9000, 4.7);
        list.addProduct("Roma Malkist Abon", 8500, 4.9);
        list.addProduct("Q-Tela Keripik Singkong", 11000, 4.8);
        list.addProduct("Aqua Botol 1.5L", 7000, 4.9);
        list.addProduct("Sprite Kaleng", 6500, 4.7);
        list.addProduct("Frestea Teh Apel", 5500, 4.6);
        list.addProduct("Nutrisari Jeruk Peras", 1500, 4.8);
        list.addProduct("Sarimi Isi 2 Ayam Bawang", 4200, 4.7);
        list.addProduct("La Fonte Saus Pasta", 24000, 4.9);
        list.addProduct("Milo Sachet", 3500, 5.0);
        list.addProduct("Dancow Bubuk Coklat", 45000, 4.8);
        list.addProduct("Blue Band Margarin", 9500, 4.7);
        list.addProduct("Royco Kaldu Ayam", 500, 4.9);
        list.addProduct("Masako Sapi", 500, 4.8);
        list.addProduct("Sajiku Tepung Bumbu", 3000, 4.7);
        list.addProduct("Sunlight Cuci Piring", 14000, 5.0);
        list.addProduct("Wipol Pembersih Lantai", 16000, 4.9);
        list.addProduct("Baygon Semprot", 35000, 4.8);
        list.addProduct("Stella Pengharum Ruangan", 28000, 4.7);
        list.addProduct("Pepsodent Pasta Gigi", 13000, 4.9);
        list.addProduct("Lifebuoy Sabun Batang", 4200, 4.8);
        list.addProduct("Sunsilk Shampo", 24000, 4.7);
        list.addProduct("Rexona Deodorant", 19000, 4.9);
        list.addProduct("Citra Body Lotion", 21000, 4.8);
        list.addProduct("Kapal Api Kopi Bubuk", 15000, 5.0);
        list.addProduct("Luwak White Koffie", 2800, 4.9);
        list.addProduct("Torabika Cappuccino", 3000, 4.8);
        list.addProduct("Indofood Bumbu Racik", 2500, 4.7);
        list.addProduct("Tolak Angin Cair", 4000, 5.0);
        list.addProduct("Antangin JRG", 3500, 4.9);
        list.addProduct("Bodrex Tablet", 2500, 4.8);
        list.addProduct("OBH Combi Batuk", 18000, 4.7);
        list.addProduct("Jus Jambu Merah", 6500, 4.6);
        list.addProduct("Cheetos Jagung Bakar", 2500, 4.8);
        list.addProduct("Sari Roti Roti Sobek", 15000, 4.9);
        list.addProduct("Kopiko Kopi Sachet", 2000, 5.0);

        System.out.println("Product Awal");
        list.display();
        System.out.println();

        int[] perbandinganPertukaran = {0,0};

        System.out.println("=====================");
        System.out.println("SEARCHING");
        System.out.println("=====================");

        System.out.println("Mencari Product dengan nama : \"Jus Jambu Merah\" dengan metode Linear Search");
        ListProduct linearSearch = list.copyList();
        long startTime = System.nanoTime();
        linearSearch.linearSearch("Jus Jambu Merah");
        long endTime = System.nanoTime();
        double waktu = (double)(endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pencarian: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mencari Product dengan nama : \"Jus Jambu Merah\" dengan metode Binary Search");
        ListProduct binarySearch = list.copyList();
        startTime = System.nanoTime();
        binarySearch.selectionSort("nama", "asc");
        binarySearch.binarySearch("Jus Jambu Merah");
        endTime = System.nanoTime();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pencarian: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("=====================");
        System.out.println("BUBBLE ASC SORT");
        System.out.println("=====================");


        System.out.println("Mengurutkan Product berdasarkan harga secara Ascending dengan metode Bubble Sort");
        ListProduct bubbleAscHarga = list.copyList(); 
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleAscHarga.bubbleSort("harga", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan nama secara Ascending dengan metode Bubble Sort");
        ListProduct bubbleAscNama = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleAscNama.bubbleSort("nama", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // bubbleAscNama.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan rating secara Ascending dengan metode Bubble Sort");
        ListProduct bubbleAscRating = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleAscRating.bubbleSort("rating", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("=====================");
        System.out.println("SELECTION ASC SORT");
        System.out.println("=====================");
        
        System.out.println("Mengurutkan Product berdasarkan harga secara Ascending dengan metode Selection Sort");
        ListProduct selectionAscHarga = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionAscHarga.selectionSort("harga", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan nama secara Ascending dengan metode Selection Sort");
        ListProduct selectionAscNama = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionAscNama.selectionSort("nama", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan rating secara Ascending dengan metode Selection Sort");
        ListProduct selectionAscRating = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionAscRating.selectionSort("rating", "asc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("=====================");
        System.out.println("BUBBLE DESC SORT");
        System.out.println("=====================");

        System.out.println("Mengurutkan Product berdasarkan harga secara Descending dengan metode Bubble Sort");
        ListProduct bubbleDescHarga = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleDescHarga.bubbleSort("harga", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan nama secara Descending dengan metode Bubble Sort");
        ListProduct bubbleDescNama = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleDescNama.bubbleSort("nama", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan rating secara Descending dengan metode Bubble Sort");
        ListProduct bubbleDescRating = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = bubbleDescRating.bubbleSort("rating", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("=====================");
        System.out.println("SELECTION DESC SORT");
        System.out.println("=====================");
        
        System.out.println("Mengurutkan Product berdasarkan harga secara Descending dengan metode Selection Sort");
        ListProduct selectionDescHarga = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionDescHarga.selectionSort("harga", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan nama secara Descending dengan metode Selection Sort");
        ListProduct selectionDescNama = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionDescNama.selectionSort("nama", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan rating secara Descending dengan metode Selection Sort");
        ListProduct selectionDescRating = list.copyList();
        startTime = System.nanoTime();
        perbandinganPertukaran = selectionDescRating.selectionSort("rating", "desc");
        endTime = System.nanoTime();
        System.out.println("Jumlah perbandingan data: " + perbandinganPertukaran[0]);
        System.out.println("Jumlah pertukaran data: " + perbandinganPertukaran[1]);
        // list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
    }
}
