public class Main {

    public static void main(String[] args) throws Exception {
        ListProduct list = new ListProduct();

        list.addProduct("Ultramilk", 7000, 4.8);
        list.addProduct("Clevo", 3000, 2.5);
        list.addProduct("Bear Brend", 10000, 3.5);
        list.addProduct("Greenfield", 7500, 4);
        list.addProduct("Oreo", 12000, 4.8);
        list.addProduct("Indomilk", 8000, 4.95);
        list.addProduct("Japota", 10000, 4.3);
        list.addProduct("Chocolatos Keju", 7000, 2.5);
        list.addProduct("Sarimi Isi 2", 4000, 4.4);
        list.addProduct("Pillow", 5000, 5);
        list.addProduct("Lifebuoy", 4000, 4.7);
        list.addProduct("Dettol", 4500, 4.9);
        list.addProduct("Chitato", 13000, 5);
        list.addProduct("Supermi", 2800, 4.2);
        list.addProduct("Giv", 3000, 4.4);
        list.addProduct("Shinzui", 5000, 4.8);
        list.addProduct("Rinso", 25000, 4.8);
        list.addProduct("Daia", 18000, 4.5);
        list.addProduct("Nuvo", 3500, 4.5);
        list.addProduct("Attack", 28000, 4.9);
        list.addProduct("Indomie Goreng", 3500, 5.0);
        list.addProduct("So Klin", 22000, 4.6);
        list.addProduct("Mie Sedaap", 3000, 4.8);
        list.addProduct("Pop Mie", 6000, 4.6);
        list.addProduct("Boom", 15000, 4.3);
        list.addProduct("Teh Botol Sosro", 5000, 4.8);
        list.addProduct("Aqua 600ml", 3500, 4.9);
        list.addProduct("Pocari Sweat", 7000, 4.7);
        list.addProduct("Sprite", 6000, 5);
        list.addProduct("Coca-Cola", 6000, 4.5);
        list.addProduct("Kopi Instan Gayo", 25000, 4.9);
        list.addProduct("Teh Melati Celup", 15000, 4.7);
        list.addProduct("Susu UHT Coklat 1L", 18000, 4.8);
        list.addProduct("Biskuit Kelapa Renyah", 9500, 4.5);
        list.addProduct("Keripik Singkong Balado", 12000, 4.6);
        list.addProduct("Sereal Gandum Madu", 32000, 4.7);
        list.addProduct("Jus Jambu Merah", 8000, 4.4);
        list.addProduct("Mie Instan Kari Spesial", 3500, 5.0);
        // list.addProduct("Sarden Saus Tomat", 11000, 4.3);
        // list.addProduct("Minyak Goreng Kelapa 2L", 38000, 4.8);
        // list.addProduct("Beras Pandan Wangi 5kg", 65000, 4.9);
        // list.addProduct("Kecap Manis Refill", 14000, 4.7);
        // list.addProduct("Sambal Terasi Sachet", 2000, 4.9);
        // list.addProduct("Tepung Terigu Serbaguna", 13000, 4.6);
        // list.addProduct("Gula Pasir Kristal 1kg", 16000, 4.5);
        // list.addProduct("Sabun Mandi Lavender", 4500, 4.8);
        // list.addProduct("Shampo Anti Ketombe", 22000, 4.7);
        // list.addProduct("Pasta Gigi Herbal", 9000, 4.6);
        // list.addProduct("Deterjen Cair Konsentrat", 28000, 4.9);
        // list.addProduct("Pelembut Pakaian Floral", 19000, 4.7);
        // list.addProduct("Obat Nyamuk Elektrik", 25000, 4.4);
        // list.addProduct("Baterai AA (Isi 4)", 15000, 4.5);
        // list.addProduct("Lampu LED 10 Watt", 20000, 4.8);
        // list.addProduct("Kabel Data USB-C", 45000, 4.7);
        // list.addProduct("Powerbank 10000mAh", 150000, 4.9);
        // list.addProduct("Mouse Wireless Silent", 120000, 4.8);
        // list.addProduct("Keyboard Mekanikal Mini", 450000, 5.0);
        // list.addProduct("Headset Gaming RGB", 350000, 4.7);
        // list.addProduct("Webcam Full HD", 280000, 4.6);
        // list.addProduct("Speaker Bluetooth Portabel", 220000, 4.8);
        // list.addProduct("Yogurt Drink Strawberry", 9000, 4.9);
        // list.addProduct("Sosis Sapi Bakar (Isi 6)", 24000, 4.7);
        // list.addProduct("Nugget Ayam Original", 27000, 4.6);
        // list.addProduct("Keju Cheddar Blok", 21000, 4.8);
        // list.addProduct("Mentega Asin", 8000, 4.5);
        // list.addProduct("Selai Coklat Hazelnut", 35000, 4.9);
        // list.addProduct("Roti Tawar Gandum", 16000, 4.7);
        // list.addProduct("Madu Hutan Asli", 75000, 5.0);
        // list.addProduct("Air Mineral 600ml", 3500, 4.9);
        // list.addProduct("Minuman Isotonik Lemon", 7000, 4.6);
        // list.addProduct("Tisu Wajah 250 sheet", 14000, 4.7);
        // list.addProduct("Pembersih Lantai Sereh", 12000, 4.8);
        // list.addProduct("Sabun Cuci Piring Jeruk Nipis", 13000, 4.9);
        // list.addProduct("Popok Bayi (Ukuran M)", 55000, 4.8);
        // list.addProduct("Minyak Kayu Putih", 28000, 4.9);
        // list.addProduct("Balsem Otot", 18000, 4.7);
        // list.addProduct("Plester Luka Anti Air", 9000, 4.6);
        // list.addProduct("Deodorant Roll-On", 17000, 4.5);
        // list.addProduct("Parfum Eau de Toilette", 125000, 4.8);
        // list.addProduct("Masker Wajah Green Tea", 15000, 4.9);
        // list.addProduct("Kapas Kecantikan", 10000, 4.7);
        // list.addProduct("Buku Tulis (Isi 10)", 38000, 4.6);
        // list.addProduct("Pulpen Gel Hitam", 5000, 4.8);
        // list.addProduct("Spidol Papan Tulis", 8000, 4.5);
        // list.addProduct("Lem Kertas Stik", 4000, 4.4);
        // list.addProduct("Penghapus Pensil", 2500, 4.7);
        // list.addProduct("Cokelat Batang Almond", 19000, 4.9);
        // list.addProduct("Permen Kopi", 11000, 4.6);
        // list.addProduct("Wafer Keju", 8500, 4.7);
        // list.addProduct("Donat Coklat Mesis", 6000, 4.8);
        // list.addProduct("Es Krim Vanila Cup", 9000, 4.9);
        // list.addProduct("Frozen Dimsum Ayam", 42000, 4.8);
        // list.addProduct("Kentang Beku Shoestring", 33000, 4.7);
        // list.addProduct("Bakso Sapi Premium", 48000, 4.9);
        // list.addProduct("Telur Ayam Negeri (10 butir)", 24000, 4.6);
        // list.addProduct("Tahu Sutra", 7000, 4.5);
        // list.addProduct("Tempe Mendoan", 5000, 4.8);
        // list.addProduct("Sayur Bayam Segar", 4000, 4.7);
        // list.addProduct("Wortel Import", 8000, 4.6);
        // list.addProduct("Apel Fuji", 7500, 4.9);
        // list.addProduct("Pisang Ambon", 6000, 4.8);
        // list.addProduct("Pewangi Ruangan Otomatis", 45000, 4.7);
        // list.addProduct("Kantong Sampah (Isi 30)", 15000, 4.6);
        // list.addProduct("Spons Cuci Piring", 3000, 4.5);
        // list.addProduct("Kain Lap Mikrofiber", 12000, 4.8);
        // list.addProduct("Sapu Ijuk", 25000, 4.4);
        // list.addProduct("Obeng Set Mini", 55000, 4.7);
        // list.addProduct("Gembok Anti Karat", 40000, 4.6);
        // list.addProduct("Lakban Bening", 9000, 4.5);
        // list.addProduct("Gunting Serbaguna", 11000, 4.8);
        // list.addProduct("Payung Lipat Otomatis", 85000, 4.9);
        // list.addProduct("Jas Hujan Ponco", 35000, 4.6);
        // list.addProduct("Sandal Jepit Karet", 20000, 4.7);
        // list.addProduct("Kaos Kaki Olahraga", 18000, 4.8);
        // list.addProduct("Topi Baseball Polos", 50000, 4.9);
        // list.addProduct("Ikat Rambut (Isi 12)", 10000, 4.5);
        // list.addProduct("Korek Api Gas", 3000, 4.3);
        // list.addProduct("Lilin Aromaterapi", 30000, 4.8);
        // list.addProduct("Pupuk Tanaman Hias", 15000, 4.7);
        // list.addProduct("Pot Bunga Plastik", 12000, 4.6);
        // list.addProduct("Makanan Kucing Kering 1kg", 45000, 4.9);
        // list.addProduct("Pasir Gumpal Kucing 5L", 50000, 4.8);
        // list.addProduct("Akuarium Mini", 100000, 4.7);
        // list.addProduct("Filter Air Keran", 60000, 4.6);
        // list.addProduct("Bohlam Pijar 5 Watt", 5000, 4.2);
        // list.addProduct("Steker Listrik T", 15000, 4.5);

        System.out.println("Product Awal");
        list.display();
        System.out.println();

        System.out.println("Mencari Product dengan nama : \"Jus Jambu Merah\" dengan metode Linear Search");
        long startTime = System.nanoTime();
        list.linearSearch("Jus Jambu Merah");
        long endTime = System.nanoTime();
        double waktu = (double)(endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pencarian: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mencari Product dengan nama : \"Jus Jambu Merah\" dengan metode Binary Search");
        startTime = System.nanoTime();
        list.binarySearch("Jus Jambu Merah");
        endTime = System.nanoTime();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pencarian: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan harga secara Ascending dengan metode Bubble Sort");
        startTime = System.nanoTime();
        list.bubbleSort("harga", "asc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan nama secara Ascending dengan metode Bubble Sort");
        startTime = System.nanoTime();
        list.bubbleSort("nama", "asc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan rating secara Ascending dengan metode Bubble Sort");
        startTime = System.nanoTime();
        list.bubbleSort("rating", "asc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan harga secara Descending dengan metode Selection Sort");
        startTime = System.nanoTime();
        list.selectionSort("harga", "desc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
        
        System.out.println("Mengurutkan Product berdasarkan nama secara Descending dengan metode Selection Sort");
        startTime = System.nanoTime();
        list.selectionSort("nama", "desc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();

        System.out.println("Mengurutkan Product berdasarkan rating secara Descending dengan metode Selection Sort");
        startTime = System.nanoTime();
        list.selectionSort("rating", "desc");
        endTime = System.nanoTime();
        list.display();
        waktu = (double) (endTime - startTime)/1000000000.0;
        System.out.printf("Waktu pengurutan: %8f detik", waktu);
        System.out.println();
        System.out.println();
    }
}
